export interface Nation {
  name: string;
  flag: string;
}

export const fifaNations: Nation[] = [
  { name: 'Afganistán', flag: '🇦🇫' },
  { name: 'Albania', flag: '🇦🇱' },
  { name: 'Alemania', flag: '🇩🇪' },
  { name: 'Andorra', flag: '🇦🇩' },
  { name: 'Angola', flag: '🇦🇴' },
  { name: 'Anguila', flag: '🇦🇮' },
  { name: 'Antigua y Barbuda', flag: '🇦🇬' },
  { name: 'Arabia Saudita', flag: '🇸🇦' },
  { name: 'Argelia', flag: '🇩🇿' },
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'Armenia', flag: '🇦🇲' },
  { name: 'Aruba', flag: '🇦🇼' },
  { name: 'Australia', flag: '🇦🇺' },
  { name: 'Austria', flag: '🇦🇹' },
  { name: 'Azerbaiyán', flag: '🇦🇿' },
  { name: 'Bahamas', flag: '🇧🇸' },
  { name: 'Bangladés', flag: '🇧🇩' },
  { name: 'Barbados', flag: '🇧🇧' },
  { name: 'Baréin', flag: '🇧🇭' },
  { name: 'Bélgica', flag: '🇧🇪' },
  { name: 'Belice', flag: '🇧🇿' },
  { name: 'Benín', flag: '🇧🇯' },
  { name: 'Bermudas', flag: '🇧🇲' },
  { name: 'Bielorrusia', flag: '🇧🇾' },
  { name: 'Birmania', flag: '🇲🇲' },
  { name: 'Bolivia', flag: '🇧🇴' },
  { name: 'Bonaire', flag: '🇧🇶' },
  { name: 'Bosnia y Herzegovina', flag: '🇧🇦' },
  { name: 'Botsuana', flag: '🇧🇼' },
  { name: 'Brasil', flag: '🇧🇷' },
  { name: 'Brunéi', flag: '🇧🇳' },
  { name: 'Bulgaria', flag: '🇧🇬' },
  { name: 'Burkina Faso', flag: '🇧🇫' },
  { name: 'Burundi', flag: '🇧🇮' },
  { name: 'Bután', flag: '🇧🇹' },
  { name: 'Cabo Verde', flag: '🇨🇻' },
  { name: 'Camboya', flag: '🇰🇭' },
  { name: 'Camerún', flag: '🇨🇲' },
  { name: 'Canadá', flag: '🇨🇦' },
  { name: 'Catar', flag: '🇶🇦' },
  { name: 'Chad', flag: '🇹🇩' },
  { name: 'Chile', flag: '🇨🇱' },
  { name: 'China', flag: '🇨🇳' },
  { name: 'China Taipéi', flag: '🇹🇼' },
  { name: 'Chipre', flag: '🇨🇾' },
  { name: 'Colombia', flag: '🇨🇴' },
  { name: 'Comoras', flag: '🇰🇲' },
  { name: 'Congo', flag: '🇨🇬' },
  { name: 'Corea del Norte', flag: '🇰🇵' },
  { name: 'Corea del Sur', flag: '🇰🇷' },
  { name: 'Costa de Marfil', flag: '🇨🇮' },
  { name: 'Costa Rica', flag: '🇨🇷' },
  { name: 'Croacia', flag: '🇭🇷' },
  { name: 'Cuba', flag: '🇨🇺' },
  { name: 'Curazao', flag: '🇨🇼' },
  { name: 'Dinamarca', flag: '🇩🇰' },
  { name: 'Dominica', flag: '🇩🇲' },
  { name: 'Ecuador', flag: '🇪🇨' },
  { name: 'Egipto', flag: '🇪🇬' },
  { name: 'El Salvador', flag: '🇸🇻' },
  { name: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { name: 'Eritrea', flag: '🇪🇷' },
  { name: 'Escocia', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { name: 'España', flag: '🇪🇸' },
  { name: 'Estados Unidos', flag: '🇺🇸' },
  { name: 'Estonia', flag: '🇪🇪' },
  { name: 'Eswatini', flag: '🇸🇿' },
  { name: 'Etiopía', flag: '🇪🇹' },
  { name: 'Filipinas', flag: '🇵🇭' },
  { name: 'Finlandia', flag: '🇫🇮' },
  { name: 'Fiyi', flag: '🇫🇯' },
  { name: 'Francia', flag: '🇫🇷' },
  { name: 'Gabón', flag: '🇬🇦' },
  { name: 'Gales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { name: 'Gambia', flag: '🇬🇲' },
  { name: 'Georgia', flag: '🇬🇪' },
  { name: 'Ghana', flag: '🇬🇭' },
  { name: 'Gibraltar', flag: '🇬🇮' },
  { name: 'Granada', flag: '🇬🇩' },
  { name: 'Grecia', flag: '🇬🇷' },
  { name: 'Guadalupe', flag: '🇬🇵' },
  { name: 'Guam', flag: '🇬🇺' },
  { name: 'Guatemala', flag: '🇬🇺' },
  { name: 'Guayana Francesa', flag: '🇬🇫' },
  { name: 'Guinea', flag: '🇬🇳' },
  { name: 'Guinea-Bisáu', flag: '🇬🇼' },
  { name: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { name: 'Guyana', flag: '🇬🇾' },
  { name: 'Haití', flag: '🇭🇹' },
  { name: 'Honduras', flag: '🇭🇳' },
  { name: 'Hong Kong', flag: '🇭🇰' },
  { name: 'Hungría', flag: '🇭🇺' },
  { name: 'India', flag: '🇮🇳' },
  { name: 'Indonesia', flag: '🇮🇩' },
  { name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name: 'Irak', flag: '🇮🇶' },
  { name: 'Irán', flag: '🇮🇷' },
  { name: 'Irlanda', flag: '🇮🇪' },
  { name: 'Irlanda del Norte', flag: '🏴󠁧󠁢󠁮󠁩󠁗󠁿' },
  { name: 'Islandia', flag: '🇮🇸' },
  { name: 'Islas Caimán', flag: '🇰🇾' },
  { name: 'Islas Cook', flag: '🇨🇰' },
  { name: 'Islas Feroe', flag: '🇫🇴' },
  { name: 'Islas Marianas del Norte', flag: '🇲🇵' },
  { name: 'Islas Salomón', flag: '🇸🇧' },
  { name: 'Islas Turcas y Caicos', flag: '🇹🇨' },
  { name: 'Islas Vírgenes Británicas', flag: '🇻🇬' },
  { name: 'Islas Vírgenes de los Estados Unidos', flag: '🇻🇮' },
  { name: 'Israel', flag: '🇮🇱' },
  { name: 'Italia', flag: '🇮🇹' },
  { name: 'Jamaica', flag: '🇯🇲' },
  { name: 'Japón', flag: '🇯🇵' },
  { name: 'Jordania', flag: '🇯🇴' },
  { name: 'Kazajistán', flag: '🇰🇿' },
  { name: 'Kenia', flag: '🇰🇪' },
  { name: 'Kirguistán', flag: '🇰🇬' },
  { name: 'Kiribati', flag: '🇰🇮' },
  { name: 'Kosovo', flag: '🇽🇰' },
  { name: 'Kuwait', flag: '🇰🇼' },
  { name: 'Laos', flag: '🇱🇦' },
  { name: 'Lesoto', flag: '🇱🇸' },
  { name: 'Letonia', flag: '🇱🇻' },
  { name: 'Líbano', flag: '🇱🇧' },
  { name: 'Liberia', flag: '🇱🇷' },
  { name: 'Libia', flag: '🇱🇾' },
  { name: 'Liechtenstein', flag: '🇱🇮' },
  { name: 'Lituania', flag: '🇱🇹' },
  { name: 'Luxemburgo', flag: '🇱🇺' },
  { name: 'Macao', flag: '🇲🇴' },
  { name: 'Macedonia del Norte', flag: '🇲🇰' },
  { name: 'Madagascar', flag: '🇲🇬' },
  { name: 'Malasia', flag: '🇲🇾' },
  { name: 'Malaui', flag: '🇲🇼' },
  { name: 'Maldivas', flag: '🇲🇻' },
  { name: 'Malí', flag: '🇲🇱' },
  { name: 'Malta', flag: '🇲🇹' },
  { name: 'Marruecos', flag: '🇲🇦' },
  { name: 'Martinica', flag: '🇲🇶' },
  { name: 'Mauricio', flag: '🇲🇺' },
  { name: 'Mauritania', flag: '🇲🇷' },
  { name: 'México', flag: '🇲🇽' },
  { name: 'Moldavia', flag: '🇲🇩' },
  { name: 'Mongolia', flag: '🇲🇳' },
  { name: 'Montenegro', flag: '🇲🇪' },
  { name: 'Montserrat', flag: '🇲🇸' },
  { name: 'Mozambique', flag: '🇲🇿' },
  { name: 'Namibia', flag: '🇳🇦' },
  { name: 'Nepal', flag: '🇳🇵' },
  { name: 'Nicaragua', flag: '🇳🇮' },
  { name: 'Níger', flag: '🇳🇪' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Noruega', flag: '🇳🇴' },
  { name: 'Nueva Caledonia', flag: '🇳🇨' },
  { name: 'Nueva Zelanda', flag: '🇳🇿' },
  { name: 'Omán', flag: '🇴🇲' },
  { name: 'Países Bajos', flag: '🇳🇱' },
  { name: 'Pakistán', flag: '🇵🇰' },
  { name: 'Palestina', flag: '🇵🇸' },
  { name: 'Panamá', flag: '🇵🇦' },
  { name: 'Papúa Nueva Guinea', flag: '🇵🇬' },
  { name: 'Paraguay', flag: '🇵🇾' },
  { name: 'Perú', flag: '🇵🇪' },
  { name: 'Polonia', flag: '🇵🇱' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Puerto Rico', flag: '🇵🇷' },
  { name: 'República Centroafricana', flag: '🇨🇫' },
  { name: 'República Checa', flag: '🇨🇿' },
  { name: 'República Democrática del Congo', flag: '🇨🇩' },
  { name: 'República Dominicana', flag: '🇩🇴' },
  { name: 'Reunión', flag: '🇷🇪' },
  { name: 'Rumanía', flag: '🇷🇴' },
  { name: 'Ruanda', flag: '🇷🇼' },
  { name: 'Rusia', flag: '🇷🇺' },
  { name: 'Saint-Martin', flag: '🇲🇫' },
  { name: 'Samoa', flag: '🇼🇸' },
  { name: 'Samoa Americana', flag: '🇦🇸' },
  { name: 'San Cristóbal y Nieves', flag: '🇰🇳' },
  { name: 'San Marino', flag: '🇸🇲' },
  { name: 'San Vicente y las Granadinas', flag: '🇻🇨' },
  { name: 'Santa Lucía', flag: '🇱🇨' },
  { name: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
  { name: 'Senegal', flag: '🇸🇳' },
  { name: 'Serbia', flag: '🇷🇸' },
  { name: 'Seychelles', flag: '🇸🇨' },
  { name: 'Sierra Leona', flag: '🇸🇱' },
  { name: 'Sint Maarten', flag: '🇸🇽' },
  { name: 'Singapur', flag: '🇸🇬' },
  { name: 'Siria', flag: '🇸🇾' },
  { name: 'Somalia', flag: '🇸🇴' },
  { name: 'Sri Lanka', flag: '🇱🇰' },
  { name: 'Sudáfrica', flag: '🇿🇦' },
  { name: 'Sudán', flag: '🇸🇩' },
  { name: 'Sudán del Sur', flag: '🇸🇸' },
  { name: 'Suecia', flag: '🇸🇪' },
  { name: 'Suiza', flag: '🇨🇭' },
  { name: 'Surinam', flag: '🇸🇷' },
  { name: 'Tahití', flag: '🇵🇫' },
  { name: 'Tailandia', flag: '🇹🇭' },
  { name: 'Tanzania', flag: '🇹🇿' },
  { name: 'Tayikistán', flag: '🇹🇯' },
  { name: 'Timor Oriental', flag: '🇹🇱' },
  { name: 'Togo', flag: '🇹🇬' },
  { name: 'Tonga', flag: '🇹🇴' },
  { name: 'Trinidad y Tobago', flag: '🇹🇹' },
  { name: 'Túnez', flag: '🇹🇳' },
  { name: 'Turquía', flag: '🇹🇷' },
  { name: 'Turkmenistán', flag: '🇹🇲' },
  { name: 'Tuvalu', flag: '🇹🇻' },
  { name: 'Ucrania', flag: '🇺🇦' },
  { name: 'Uganda', flag: '🇺🇬' },
  { name: 'Uruguay', flag: '🇺🇾' },
  { name: 'Uzbekistán', flag: '🇺🇿' },
  { name: 'Vanuatu', flag: '🇻🇺' },
  { name: 'Venezuela', flag: '🇻🇪' },
  { name: 'Vietnam', flag: '🇻🇳' },
  { name: 'Yemen', flag: '🇾🇪' },
  { name: 'Yibuti', flag: '🇩🇯' },
  { name: 'Zambia', flag: '🇿🇲' },
  { name: 'Zanzíbar', flag: '🇹🇿' },
  { name: 'Zimbabue', flag: '🇿🇼' }
];
